name: aiche
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+9

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.0.2
  connectivity_plus: ^7.0.0
  conditional_builder_null_safety: ^0.0.6
  dio: ^5.4.1
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  bloc: ^9.0.0
  loading_indicator: ^3.1.1
  fluttertoast: ^8.1.1
  flutter_bloc: ^9.1.1
  image_picker: ^1.1.2
  dotted_border: ^3.1.0
  http_parser: ^4.0.0
  intl: ^0.20.2
  url_launcher: ^6.2.0
  hexcolor: ^3.0.1
  responsive_framework: ^1.1.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.6
  iconsax: ^0.0.8
  awesome_notifications_core: ^0.10.0
  awesome_notifications: ^0.10.0
  carousel_slider: ^5.0.0
  pretty_dio_logger: ^1.4.0
  sign_in_button: ^4.0.1
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.1
  flutter_staggered_animations: ^1.1.1
  font_awesome_flutter: ^10.7.0
  # Temporarily removed due to build issues
  # flutter_local_notifications: ^12.0.4
  timezone: ^0.10.1
  path_provider: ^2.1.2
  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  uuid: ^4.3.3
  # Firebase - Updated to latest compatible versions
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  crypto: ^3.0.3
  share_plus: ^12.0.0
  flutter_launcher_icons: ^0.14.3
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/
