// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Updated to match google-services.json
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2ESvC8xv8oF-D9xDQiO1qpbHxNg-1BC8',
    appId: '1:673533378711:android:a97df779f6d726bf6b29d2',
    messagingSenderId: '673533378711',
    projectId: 'ahiche-3ec5d',
    storageBucket: 'ahiche-3ec5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2ESvC8xv8oF-D9xDQiO1qpbHxNg-1BC8',
    appId:
        '1:673533378711:ios:a97df779f6d726bf6b29d2', // You may need to create iOS app in Firebase console
    messagingSenderId: '673533378711',
    projectId: 'ahiche-3ec5d',
    storageBucket: 'ahiche-3ec5d.firebasestorage.app',
    iosBundleId: 'com.aiche.aiche',
  );
}
